#!/bin/sh

echo "building Rust library..."
cargo build --release

if [ $? -eq 0 ]; then
    echo "Rust library built successfully at $(pwd)/target/release/libtambanokano.so"
    ls -la target/release/libtambanokano.so
else
    echo "Rust build failed!"
    exit 1
fi
