[package]
name = "tambanokano"
version = "0.1.0"
edition = "2021"

[lib]
name = "tambanokano"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.8"
num-complex="0.4"
image = "0.24"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
